# setting: vanilla-dynamics
# method: PAC-Base/PAC-RP, posterior
env:
  venv_seed: 0
  name: vanilla
  dataset: /home/kaichieh/slr/data/ds/vanilla/dynamics/train_posterior_1000.pkl
  action_dim: 2
  action_mag: 1.0
  use_append: true
  obs_buffer: 0.0
  g_x_fail: 1.0
  terminal_type: const
  img_h: 48
  img_w: 48
  max_step_train: 200
  max_step_eval: 200
  obs_channel: 3
  fixed_init: true
  sparse_reward: false
  num_env_train: 1000
  reward_type: task  # changes to all for PAC-RP
  reward_goal: 10
  reward_wander: 2
  reward_obs: -10

agent:
  use_wandb: true
  device: cuda:0
  image_device: cpu
  num_cpus: 8
  num_gpu_envs: null
  cpu_offset: 0
  seed: 0
  entity: pac-saferl
  project: posterior_vanilla
  run: dyn_pac_base  # wandb name
  out_folder: /scratch/gpfs/kaichieh/slr/checkpoint/vanilla/lab_dyn_pac_base/0
  name: PolicyPosteriorBasePAC  # agent name
  save_top_k: 20
  save_metric: perf
  max_steps: 500000
  memory_capacity: 50000
  check_opt_freq: 5
  min_steps_b4_opt: 2000
  optimize_freq: 2000
  update_per_opt: 1000
  disc_update_per_opt: 100
  num_visualize_task: 3
  check_type: all_env
  num_traj_per_env: 1
  # num_validation_trajs: 200
  plot_v: true
  random_init: true
  use_append_noise: false
  perf_diversity_type: state
  #
  delta: 0.01

performance:
  train:
    eval: false
    device: cuda:0
    batch_size: 256
    update_period: 1
    alpha: 0.00000001
    learn_alpha: false
    gamma: 0.99
    gamma_schedule: false
    lr_a: 0.0001  #! not used
    lr_al: 0.0001  #! not used
    lr_c: 0.0001
    lr_a_schedule: false  #! not used
    lr_al_schedule: false  #! not used
    lr_c_schedule: false
    mode: performance
    tau: 0.01
    terminal_type: none
    # latent
    lr_d: 0.0001
    disc_batch_size: 32
    disc_recent_size: 10000
    aug_reward_range_schedule: false
    aug_reward_range: 2.0
    latent_dim: 20
    latent_dim_cnn: 0
    latent_prior_std: 2
    #
    actor_path: /scratch/gpfs/kaichieh/slr/checkpoint/vanilla/sim_pac_base/0/model/performance/actor/actor-500000.pth
    critic_path: null
    #
    div_weight: 1.0
    bound_type: kl
    lr_lm: 0.0001
    lr_ll: 0.0001
  arch:
    critic_has_act_ind: false
    act_ind:
      - 1
    activation:
      actor: ReLU
      critic: ReLU
    kernel_size:
    - 5
    - 3
    - 3
    stride:
    - 2
    - 2
    - 2
    n_channel:
    - 8
    - 16
    - 32
    mlp_dim:
      actor:
      - 128
      - 128
      critic:
      - 128
      - 128
    append_dim: 2
    use_bn: false
    use_ln: true
    use_sm: false