# setting: vanilla-normal
# method: Shield, posterior
env:
  venv_seed: 0
  name: vanilla
  dataset: /home/kaichieh/slr/data/ds/vanilla/dynamics/train_posterior_1000.pkl
  action_dim: 2
  action_mag: 1.0
  use_append: true
  obs_buffer: 0.0
  g_x_fail: 1.0
  terminal_type: const
  img_h: 48
  img_w: 48
  max_step_train: 200
  max_step_eval: 200
  obs_channel: 3
  fixed_init: true
  sparse_reward: false
  num_env_train: 1000
  reward_type: task
  reward_goal: 10
  reward_wander: 2
  reward_obs: -10

agent:
  use_wandb: true
  device: cuda:0
  image_device: cpu
  num_cpus: 8
  num_gpu_envs: null
  cpu_offset: 0
  seed: 0
  entity: pac-saferl
  project: posterior_vanilla
  run: dyn_shield  # wandb name
  out_folder: /scratch/gpfs/kaichieh/slr/checkpoint/vanilla/lab_dyn_shield/0
  name: PolicyPosteriorShield  # agent name
  save_top_k: 20
  save_metric: value
  max_steps: 500000
  memory_capacity: 50000
  check_opt_freq: 5
  min_steps_b4_opt: 2000
  optimize_freq: 2000
  update_per_opt: 1000
  num_visualize_task: 3
  check_type: all_env
  num_traj_per_env: 1
  # num_validation_trajs: 200
  plot_v: true
  random_init: true
  #
  shield_dict:
    threshold: -0.05
    type: value
  #
  use_append_noise: false

performance:
  train:
    eval: false
    device: cuda:0
    batch_size: 128
    update_period: 1
    alpha: 0.1
    learn_alpha: true
    gamma: 0.99
    gamma_schedule: false
    lr_a: 0.0001
    lr_al: 0.0001
    lr_c: 0.0001
    lr_a_schedule: false
    lr_al_schedule: false
    lr_c_schedule: false
    mode: performance
    tau: 0.01
    terminal_type: none
    # latent
    latent_dim: 0
    latent_dim_cnn: 0
    #
    actor_path: /scratch/gpfs/kaichieh/slr/checkpoint/vanilla/sim_shield/0/model/performance/actor/actor-500000.pth
    critic_path: /scratch/gpfs/kaichieh/slr/checkpoint/vanilla/sim_shield/0/model/performance/critic/critic-500000.pth
  arch:
    critic_has_act_ind: false
    act_ind:
      - 1
    activation:
      actor: ReLU
      critic: ReLU
    kernel_size:
    - 5
    - 3
    - 3
    stride:
    - 2
    - 2
    - 2
    n_channel:
    - 8
    - 16
    - 32
    mlp_dim:
      actor:
      - 128
      - 128
      critic:
      - 128
      - 128
    append_dim: 2
    use_bn: false
    use_ln: true
    use_sm: false

backup:
  train:
    eval: false
    device: cuda:0
    alpha: 0.1
    learn_alpha: true
    batch_size: 128
    gamma: 0.999
    gamma_schedule: false
    lr_a: 0.0001
    lr_al: 0.0001
    lr_c: 0.0001
    lr_a_schedule: false
    lr_al_schedule: false
    lr_c_schedule: false
    mode: safety
    tau: 0.01
    terminal_type: null
    # latent
    latent_dim: 0
    latent_dim_cnn: 0
    #
    actor_path: /scratch/gpfs/kaichieh/slr/checkpoint/vanilla/sim_shield/0/model/backup/actor/actor-460000.pth
    critic_path: /scratch/gpfs/kaichieh/slr/checkpoint/vanilla/sim_shield/0/model/backup/critic/critic-460000.pth
  arch:
    critic_has_act_ind: true
    act_ind:
      - -1
    activation:
      actor: ReLU
      critic: ReLU
    kernel_size:
    - 5
    - 3
    - 3
    stride:
    - 2
    - 2
    - 2
    n_channel:
    - 8
    - 16
    - 32
    mlp_dim:
      actor:
      - 128
      - 128
      critic:
      - 128
      - 128
    append_dim: 2
    use_bn: false
    use_ln: true
    use_sm: false
