vis: 1
env-name: "2DNavigation-v0"
latent_size: 10
sparse_reward: true

gamma: 0.99
gae-lambda: 1.0
first-order: false
hidden-sizes: [100, 100]
nonlinearity: "tanh"

fast-batch-size: 50
num-steps: 1
fast-lr: 10

num-batches: 250
num-train-task: 4
num-test-task: 50

# TRPO-specific
# -------------
# Size of the trust-region.
max-kl: 1.0e-2

# Number of iterations of Conjugate Gradient.
cg-iters: 10

# Value of the damping in Conjugate Gradient.
cg-damping: 1.0e-5

# Maximum number of steps in the line search.
ls-max-steps: 15

# Ratio to use for backtracking during the line search.
ls-backtrack-ratio: 0.8