vis: 1

env-name: "Pusher-v0"
latent_size: 2
sparse_reward: false

gamma: 0.99
gae-lambda: 1.0
first-order: false

hidden-sizes: [100, 100]
nonlinearity: "relu"

fast-batch-size: 40
num-steps: 1
fast-lr: 10
num-batches: 250
num-train-task: 20
num-test-task: 10

max-kl: 1.0e-2
cg-iters: 10
cg-damping: 1.0e-5
ls-max-steps: 15
ls-backtrack-ratio: 0.8
